//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18033
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace AeiCliente.ServiceReference3 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compra", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    public partial class Compra : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AeiCliente.ServiceReference3.Direccion DireccionField;
        
        private System.DateTime FechaEntregaField;
        
        private System.DateTime FechaSolicitudField;
        
        private int IdField;
        
        private float MontoTotalField;
        
        private AeiCliente.ServiceReference3.MetodoPago PagoField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AeiCliente.ServiceReference3.Direccion Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((this.FechaEntregaField.Equals(value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSolicitud {
            get {
                return this.FechaSolicitudField;
            }
            set {
                if ((this.FechaSolicitudField.Equals(value) != true)) {
                    this.FechaSolicitudField = value;
                    this.RaisePropertyChanged("FechaSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MontoTotal {
            get {
                return this.MontoTotalField;
            }
            set {
                if ((this.MontoTotalField.Equals(value) != true)) {
                    this.MontoTotalField = value;
                    this.RaisePropertyChanged("MontoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AeiCliente.ServiceReference3.MetodoPago Pago {
            get {
                return this.PagoField;
            }
            set {
                if ((object.ReferenceEquals(this.PagoField, value) != true)) {
                    this.PagoField = value;
                    this.RaisePropertyChanged("Pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Direccion", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    public partial class Direccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CiudadField;
        
        private int CodigoPostalField;
        
        private string DescripcionField;
        
        private string EstadoField;
        
        private int IdField;
        
        private string PaisField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((this.CodigoPostalField.Equals(value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetodoPago", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    public partial class MetodoPago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime FechaVencimientoField;
        
        private int IdField;
        
        private string MarcaField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    public partial class Categoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tag", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    public partial class Tag : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescripcionField;
        
        private int IdField;
        
        private string ImagenDetalleField;
        
        private string ImagenMiniaturaField;
        
        private string NombreField;
        
        private float PrecioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagenDetalle {
            get {
                return this.ImagenDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenDetalleField, value) != true)) {
                    this.ImagenDetalleField = value;
                    this.RaisePropertyChanged("ImagenDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagenMiniatura {
            get {
                return this.ImagenMiniaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenMiniaturaField, value) != true)) {
                    this.ImagenMiniaturaField = value;
                    this.RaisePropertyChanged("ImagenMiniatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calificacion", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    public partial class Calificacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ComentarioField;
        
        private int IdField;
        
        private int PuntajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentario {
            get {
                return this.ComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioField, value) != true)) {
                    this.ComentarioField = value;
                    this.RaisePropertyChanged("Comentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntaje {
            get {
                return this.PuntajeField;
            }
            set {
                if ((this.PuntajeField.Equals(value) != true)) {
                    this.PuntajeField = value;
                    this.RaisePropertyChanged("Puntaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ApellidoField;
        
        private AeiCliente.ServiceReference3.Compra CarritoField;
        
        private string CodigoActivacionField;
        
        private System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Compra> ComprasField;
        
        private System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Direccion> DireccionesField;
        
        private string EmailField;
        
        private System.DateTime FechaNacimientoField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdField;
        
        private System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.MetodoPago> MetodosPagoField;
        
        private string NombreField;
        
        private string PasaporteField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AeiCliente.ServiceReference3.Compra Carrito {
            get {
                return this.CarritoField;
            }
            set {
                if ((object.ReferenceEquals(this.CarritoField, value) != true)) {
                    this.CarritoField = value;
                    this.RaisePropertyChanged("Carrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoActivacion {
            get {
                return this.CodigoActivacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoActivacionField, value) != true)) {
                    this.CodigoActivacionField = value;
                    this.RaisePropertyChanged("CodigoActivacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Compra> Compras {
            get {
                return this.ComprasField;
            }
            set {
                if ((object.ReferenceEquals(this.ComprasField, value) != true)) {
                    this.ComprasField = value;
                    this.RaisePropertyChanged("Compras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Direccion> Direcciones {
            get {
                return this.DireccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionesField, value) != true)) {
                    this.DireccionesField = value;
                    this.RaisePropertyChanged("Direcciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.MetodoPago> MetodosPago {
            get {
                return this.MetodosPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodosPagoField, value) != true)) {
                    this.MetodosPagoField = value;
                    this.RaisePropertyChanged("MetodosPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pasaporte {
            get {
                return this.PasaporteField;
            }
            set {
                if ((object.ReferenceEquals(this.PasaporteField, value) != true)) {
                    this.PasaporteField = value;
                    this.RaisePropertyChanged("Pasaporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IServicioDAO")]
    public interface IServicioDAO {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/GetData", ReplyAction="http://tempuri.org/IServicioDAO/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/setCompra", ReplyAction="http://tempuri.org/IServicioDAO/setCompraResponse")]
        System.Threading.Tasks.Task<int> setCompraAsync(AeiCliente.ServiceReference3.Compra compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/getListaCategoria", ReplyAction="http://tempuri.org/IServicioDAO/getListaCategoriaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Categoria>> getListaCategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/buscarProductoPorCategoria", ReplyAction="http://tempuri.org/IServicioDAO/buscarProductoPorCategoriaResponse")]
        System.Threading.Tasks.Task<AeiCliente.ServiceReference3.Categoria> buscarProductoPorCategoriaAsync(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/buscarTagPorProducto", ReplyAction="http://tempuri.org/IServicioDAO/buscarTagPorProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Tag>> buscarTagPorProductoAsync(int idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/setCantidadProducto", ReplyAction="http://tempuri.org/IServicioDAO/setCantidadProductoResponse")]
        System.Threading.Tasks.Task<int> setCantidadProductoAsync(int idProducto, int cantidadEnExistencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/getProductos", ReplyAction="http://tempuri.org/IServicioDAO/getProductosResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Producto>> getProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/getProductoPorNombre", ReplyAction="http://tempuri.org/IServicioDAO/getProductoPorNombreResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Producto>> getProductoPorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/getProductoPorCategoria", ReplyAction="http://tempuri.org/IServicioDAO/getProductoPorCategoriaResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Producto>> getProductoPorCategoriaAsync(string nombreCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/getProductoPorDetalleCompra", ReplyAction="http://tempuri.org/IServicioDAO/getProductoPorDetalleCompraResponse")]
        System.Threading.Tasks.Task<AeiCliente.ServiceReference3.Producto> getProductoPorDetalleCompraAsync(int idDetalleCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/setCalificacion", ReplyAction="http://tempuri.org/IServicioDAO/setCalificacionResponse")]
        System.Threading.Tasks.Task<int> setCalificacionAsync(int idProducto, AeiCliente.ServiceReference3.Calificacion calificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/setAgregarCompra", ReplyAction="http://tempuri.org/IServicioDAO/setAgregarCompraResponse")]
        System.Threading.Tasks.Task<int> setAgregarCompraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/setEstadoDeCompra", ReplyAction="http://tempuri.org/IServicioDAO/setEstadoDeCompraResponse")]
        System.Threading.Tasks.Task<int> setEstadoDeCompraAsync(string status, int idCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/setMetodoPago", ReplyAction="http://tempuri.org/IServicioDAO/setMetodoPagoResponse")]
        System.Threading.Tasks.Task<int> setMetodoPagoAsync(AeiCliente.ServiceReference3.MetodoPago metodo, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/getMetodoPagoPorCompra", ReplyAction="http://tempuri.org/IServicioDAO/getMetodoPagoPorCompraResponse")]
        System.Threading.Tasks.Task<AeiCliente.ServiceReference3.MetodoPago> getMetodoPagoPorCompraAsync(int idCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/setModificarMetodoPago", ReplyAction="http://tempuri.org/IServicioDAO/setModificarMetodoPagoResponse")]
        System.Threading.Tasks.Task<int> setModificarMetodoPagoAsync(AeiCliente.ServiceReference3.MetodoPago metodoModificado, int idMetodoActual, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/getDireccionDeCompra", ReplyAction="http://tempuri.org/IServicioDAO/getDireccionDeCompraResponse")]
        System.Threading.Tasks.Task<AeiCliente.ServiceReference3.Direccion> getDireccionDeCompraAsync(int idCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDAO/setUsuario", ReplyAction="http://tempuri.org/IServicioDAO/setUsuarioResponse")]
        System.Threading.Tasks.Task<int> setUsuarioAsync(AeiCliente.ServiceReference3.Usuario usuarioModificado, int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioDAOChannel : AeiCliente.ServiceReference3.IServicioDAO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDAOClient : System.ServiceModel.ClientBase<AeiCliente.ServiceReference3.IServicioDAO>, AeiCliente.ServiceReference3.IServicioDAO {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioDAOClient() : 
                base(ServicioDAOClient.GetDefaultBinding(), ServicioDAOClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioDAO.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDAOClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioDAOClient.GetBindingForEndpoint(endpointConfiguration), ServicioDAOClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDAOClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioDAOClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDAOClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioDAOClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDAOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Threading.Tasks.Task<int> setCompraAsync(AeiCliente.ServiceReference3.Compra compra) {
            return base.Channel.setCompraAsync(compra);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Categoria>> getListaCategoriaAsync() {
            return base.Channel.getListaCategoriaAsync();
        }
        
        public System.Threading.Tasks.Task<AeiCliente.ServiceReference3.Categoria> buscarProductoPorCategoriaAsync(int idProducto) {
            return base.Channel.buscarProductoPorCategoriaAsync(idProducto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Tag>> buscarTagPorProductoAsync(int idproducto) {
            return base.Channel.buscarTagPorProductoAsync(idproducto);
        }
        
        public System.Threading.Tasks.Task<int> setCantidadProductoAsync(int idProducto, int cantidadEnExistencia) {
            return base.Channel.setCantidadProductoAsync(idProducto, cantidadEnExistencia);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Producto>> getProductosAsync() {
            return base.Channel.getProductosAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Producto>> getProductoPorNombreAsync(string nombre) {
            return base.Channel.getProductoPorNombreAsync(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<AeiCliente.ServiceReference3.Producto>> getProductoPorCategoriaAsync(string nombreCategoria) {
            return base.Channel.getProductoPorCategoriaAsync(nombreCategoria);
        }
        
        public System.Threading.Tasks.Task<AeiCliente.ServiceReference3.Producto> getProductoPorDetalleCompraAsync(int idDetalleCompra) {
            return base.Channel.getProductoPorDetalleCompraAsync(idDetalleCompra);
        }
        
        public System.Threading.Tasks.Task<int> setCalificacionAsync(int idProducto, AeiCliente.ServiceReference3.Calificacion calificacion) {
            return base.Channel.setCalificacionAsync(idProducto, calificacion);
        }
        
        public System.Threading.Tasks.Task<int> setAgregarCompraAsync() {
            return base.Channel.setAgregarCompraAsync();
        }
        
        public System.Threading.Tasks.Task<int> setEstadoDeCompraAsync(string status, int idCompra) {
            return base.Channel.setEstadoDeCompraAsync(status, idCompra);
        }
        
        public System.Threading.Tasks.Task<int> setMetodoPagoAsync(AeiCliente.ServiceReference3.MetodoPago metodo, int idUsuario) {
            return base.Channel.setMetodoPagoAsync(metodo, idUsuario);
        }
        
        public System.Threading.Tasks.Task<AeiCliente.ServiceReference3.MetodoPago> getMetodoPagoPorCompraAsync(int idCompra) {
            return base.Channel.getMetodoPagoPorCompraAsync(idCompra);
        }
        
        public System.Threading.Tasks.Task<int> setModificarMetodoPagoAsync(AeiCliente.ServiceReference3.MetodoPago metodoModificado, int idMetodoActual, int idUsuario) {
            return base.Channel.setModificarMetodoPagoAsync(metodoModificado, idMetodoActual, idUsuario);
        }
        
        public System.Threading.Tasks.Task<AeiCliente.ServiceReference3.Direccion> getDireccionDeCompraAsync(int idCompra) {
            return base.Channel.getDireccionDeCompraAsync(idCompra);
        }
        
        public System.Threading.Tasks.Task<int> setUsuarioAsync(AeiCliente.ServiceReference3.Usuario usuarioModificado, int idUsuario) {
            return base.Channel.setUsuarioAsync(usuarioModificado, idUsuario);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioDAO)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioDAO)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:52896/ServicioDAO.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ServicioDAOClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioDAO);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ServicioDAOClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioDAO);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IServicioDAO,
        }
    }
}
