//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCams.Servicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetodoPago", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    [System.SerializableAttribute()]
    public partial class MetodoPago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCams.Servicio.Compra CarritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoActivacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebCams.Servicio.Compra> ComprasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebCams.Servicio.Direccion> DireccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebCams.Servicio.MetodoPago> MetodosPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasaporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCams.Servicio.Compra Carrito {
            get {
                return this.CarritoField;
            }
            set {
                if ((object.ReferenceEquals(this.CarritoField, value) != true)) {
                    this.CarritoField = value;
                    this.RaisePropertyChanged("Carrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoActivacion {
            get {
                return this.CodigoActivacionField;
            }
            set {
                if ((this.CodigoActivacionField.Equals(value) != true)) {
                    this.CodigoActivacionField = value;
                    this.RaisePropertyChanged("CodigoActivacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebCams.Servicio.Compra> Compras {
            get {
                return this.ComprasField;
            }
            set {
                if ((object.ReferenceEquals(this.ComprasField, value) != true)) {
                    this.ComprasField = value;
                    this.RaisePropertyChanged("Compras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebCams.Servicio.Direccion> Direcciones {
            get {
                return this.DireccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionesField, value) != true)) {
                    this.DireccionesField = value;
                    this.RaisePropertyChanged("Direcciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebCams.Servicio.MetodoPago> MetodosPago {
            get {
                return this.MetodosPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodosPagoField, value) != true)) {
                    this.MetodosPagoField = value;
                    this.RaisePropertyChanged("MetodosPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pasaporte {
            get {
                return this.PasaporteField;
            }
            set {
                if ((object.ReferenceEquals(this.PasaporteField, value) != true)) {
                    this.PasaporteField = value;
                    this.RaisePropertyChanged("Pasaporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compra", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    [System.SerializableAttribute()]
    public partial class Compra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCams.Servicio.Direccion DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float MontoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCams.Servicio.MetodoPago PagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebCams.Servicio.DetalleCompra> ProductosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCams.Servicio.Direccion Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((this.FechaEntregaField.Equals(value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSolicitud {
            get {
                return this.FechaSolicitudField;
            }
            set {
                if ((this.FechaSolicitudField.Equals(value) != true)) {
                    this.FechaSolicitudField = value;
                    this.RaisePropertyChanged("FechaSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MontoTotal {
            get {
                return this.MontoTotalField;
            }
            set {
                if ((this.MontoTotalField.Equals(value) != true)) {
                    this.MontoTotalField = value;
                    this.RaisePropertyChanged("MontoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCams.Servicio.MetodoPago Pago {
            get {
                return this.PagoField;
            }
            set {
                if ((object.ReferenceEquals(this.PagoField, value) != true)) {
                    this.PagoField = value;
                    this.RaisePropertyChanged("Pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebCams.Servicio.DetalleCompra> Productos {
            get {
                return this.ProductosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductosField, value) != true)) {
                    this.ProductosField = value;
                    this.RaisePropertyChanged("Productos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Direccion", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    [System.SerializableAttribute()]
    public partial class Direccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((this.CodigoPostalField.Equals(value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleCompra", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    [System.SerializableAttribute()]
    public partial class DetalleCompra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCams.Servicio.Producto ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCams.Servicio.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebCams.Servicio.Calificacion> CalificacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCams.Servicio.Categoria CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebCams.Servicio.Tag> EtiquetasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenMiniaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebCams.Servicio.Calificacion> Calificaciones {
            get {
                return this.CalificacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.CalificacionesField, value) != true)) {
                    this.CalificacionesField = value;
                    this.RaisePropertyChanged("Calificaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCams.Servicio.Categoria Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebCams.Servicio.Tag> Etiquetas {
            get {
                return this.EtiquetasField;
            }
            set {
                if ((object.ReferenceEquals(this.EtiquetasField, value) != true)) {
                    this.EtiquetasField = value;
                    this.RaisePropertyChanged("Etiquetas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagenDetalle {
            get {
                return this.ImagenDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenDetalleField, value) != true)) {
                    this.ImagenDetalleField = value;
                    this.RaisePropertyChanged("ImagenDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagenMiniatura {
            get {
                return this.ImagenMiniaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenMiniaturaField, value) != true)) {
                    this.ImagenMiniaturaField = value;
                    this.RaisePropertyChanged("ImagenMiniatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    [System.SerializableAttribute()]
    public partial class Categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calificacion", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    [System.SerializableAttribute()]
    public partial class Calificacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCams.Servicio.Usuario UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentario {
            get {
                return this.ComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioField, value) != true)) {
                    this.ComentarioField = value;
                    this.RaisePropertyChanged("Comentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntaje {
            get {
                return this.PuntajeField;
            }
            set {
                if ((this.PuntajeField.Equals(value) != true)) {
                    this.PuntajeField = value;
                    this.RaisePropertyChanged("Puntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCams.Servicio.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tag", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices")]
    [System.SerializableAttribute()]
    public partial class Tag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Twitter", Namespace="http://schemas.datacontract.org/2004/07/AeiWebServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Twitter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OauthTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OauthTokenSecretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScreenNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioField, value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OauthToken {
            get {
                return this.OauthTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.OauthTokenField, value) != true)) {
                    this.OauthTokenField = value;
                    this.RaisePropertyChanged("OauthToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OauthTokenSecret {
            get {
                return this.OauthTokenSecretField;
            }
            set {
                if ((object.ReferenceEquals(this.OauthTokenSecretField, value) != true)) {
                    this.OauthTokenSecretField = value;
                    this.RaisePropertyChanged("OauthTokenSecret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScreenName {
            get {
                return this.ScreenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreenNameField, value) != true)) {
                    this.ScreenNameField = value;
                    this.RaisePropertyChanged("ScreenName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio.IServicioAEI")]
    public interface IServicioAEI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/modificarStatusCompra", ReplyAction="http://tempuri.org/IServicioAEI/modificarStatusCompraResponse")]
        int modificarStatusCompra(int idCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/modificarStatusCompra", ReplyAction="http://tempuri.org/IServicioAEI/modificarStatusCompraResponse")]
        System.Threading.Tasks.Task<int> modificarStatusCompraAsync(int idCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/modificarMetodoPago", ReplyAction="http://tempuri.org/IServicioAEI/modificarMetodoPagoResponse")]
        WebCams.Servicio.Usuario modificarMetodoPago(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Usuario usuario, int metodoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/modificarMetodoPago", ReplyAction="http://tempuri.org/IServicioAEI/modificarMetodoPagoResponse")]
        System.Threading.Tasks.Task<WebCams.Servicio.Usuario> modificarMetodoPagoAsync(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Usuario usuario, int metodoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/generarXml", ReplyAction="http://tempuri.org/IServicioAEI/generarXmlResponse")]
        string generarXml(int idCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/generarXml", ReplyAction="http://tempuri.org/IServicioAEI/generarXmlResponse")]
        System.Threading.Tasks.Task<string> generarXmlAsync(int idCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/enviarCorreoDeFactura", ReplyAction="http://tempuri.org/IServicioAEI/enviarCorreoDeFacturaResponse")]
        int enviarCorreoDeFactura(WebCams.Servicio.Usuario usuario, WebCams.Servicio.Compra compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/enviarCorreoDeFactura", ReplyAction="http://tempuri.org/IServicioAEI/enviarCorreoDeFacturaResponse")]
        System.Threading.Tasks.Task<int> enviarCorreoDeFacturaAsync(WebCams.Servicio.Usuario usuario, WebCams.Servicio.Compra compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/agregarMetodoPago", ReplyAction="http://tempuri.org/IServicioAEI/agregarMetodoPagoResponse")]
        WebCams.Servicio.Usuario agregarMetodoPago(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/agregarMetodoPago", ReplyAction="http://tempuri.org/IServicioAEI/agregarMetodoPagoResponse")]
        System.Threading.Tasks.Task<WebCams.Servicio.Usuario> agregarMetodoPagoAsync(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/modificarDireccion", ReplyAction="http://tempuri.org/IServicioAEI/modificarDireccionResponse")]
        int modificarDireccion(WebCams.Servicio.Direccion direccionModificada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/modificarDireccion", ReplyAction="http://tempuri.org/IServicioAEI/modificarDireccionResponse")]
        System.Threading.Tasks.Task<int> modificarDireccionAsync(WebCams.Servicio.Direccion direccionModificada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/checkout", ReplyAction="http://tempuri.org/IServicioAEI/checkoutResponse")]
        WebCams.Servicio.Usuario checkout(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Direccion direccion, WebCams.Servicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/checkout", ReplyAction="http://tempuri.org/IServicioAEI/checkoutResponse")]
        System.Threading.Tasks.Task<WebCams.Servicio.Usuario> checkoutAsync(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Direccion direccion, WebCams.Servicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/disponibilidadProductos", ReplyAction="http://tempuri.org/IServicioAEI/disponibilidadProductosResponse")]
        bool disponibilidadProductos(System.Collections.Generic.List<WebCams.Servicio.DetalleCompra> detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/disponibilidadProductos", ReplyAction="http://tempuri.org/IServicioAEI/disponibilidadProductosResponse")]
        System.Threading.Tasks.Task<bool> disponibilidadProductosAsync(System.Collections.Generic.List<WebCams.Servicio.DetalleCompra> detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/checkearProductoCarrito", ReplyAction="http://tempuri.org/IServicioAEI/checkearProductoCarritoResponse")]
        bool checkearProductoCarrito(WebCams.Servicio.Usuario usuario, WebCams.Servicio.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/checkearProductoCarrito", ReplyAction="http://tempuri.org/IServicioAEI/checkearProductoCarritoResponse")]
        System.Threading.Tasks.Task<bool> checkearProductoCarritoAsync(WebCams.Servicio.Usuario usuario, WebCams.Servicio.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/borrarDetalleCarrito", ReplyAction="http://tempuri.org/IServicioAEI/borrarDetalleCarritoResponse")]
        WebCams.Servicio.Usuario borrarDetalleCarrito(WebCams.Servicio.Usuario usuario, WebCams.Servicio.DetalleCompra detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/borrarDetalleCarrito", ReplyAction="http://tempuri.org/IServicioAEI/borrarDetalleCarritoResponse")]
        System.Threading.Tasks.Task<WebCams.Servicio.Usuario> borrarDetalleCarritoAsync(WebCams.Servicio.Usuario usuario, WebCams.Servicio.DetalleCompra detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/enviarCorreoDeModificacion", ReplyAction="http://tempuri.org/IServicioAEI/enviarCorreoDeModificacionResponse")]
        int enviarCorreoDeModificacion(WebCams.Servicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/enviarCorreoDeModificacion", ReplyAction="http://tempuri.org/IServicioAEI/enviarCorreoDeModificacionResponse")]
        System.Threading.Tasks.Task<int> enviarCorreoDeModificacionAsync(WebCams.Servicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/enviarCorreoDeBienvenida", ReplyAction="http://tempuri.org/IServicioAEI/enviarCorreoDeBienvenidaResponse")]
        int enviarCorreoDeBienvenida(WebCams.Servicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/enviarCorreoDeBienvenida", ReplyAction="http://tempuri.org/IServicioAEI/enviarCorreoDeBienvenidaResponse")]
        System.Threading.Tasks.Task<int> enviarCorreoDeBienvenidaAsync(WebCams.Servicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/modificarUsuario", ReplyAction="http://tempuri.org/IServicioAEI/modificarUsuarioResponse")]
        int modificarUsuario(WebCams.Servicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/modificarUsuario", ReplyAction="http://tempuri.org/IServicioAEI/modificarUsuarioResponse")]
        System.Threading.Tasks.Task<int> modificarUsuarioAsync(WebCams.Servicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/ConsultarUsuario", ReplyAction="http://tempuri.org/IServicioAEI/ConsultarUsuarioResponse")]
        WebCams.Servicio.Usuario ConsultarUsuario(string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/ConsultarUsuario", ReplyAction="http://tempuri.org/IServicioAEI/ConsultarUsuarioResponse")]
        System.Threading.Tasks.Task<WebCams.Servicio.Usuario> ConsultarUsuarioAsync(string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/agregarUsuario", ReplyAction="http://tempuri.org/IServicioAEI/agregarUsuarioResponse")]
        WebCams.Servicio.Usuario agregarUsuario(string nombre, string apellido, string pasaporte, string mail, string fechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/agregarUsuario", ReplyAction="http://tempuri.org/IServicioAEI/agregarUsuarioResponse")]
        System.Threading.Tasks.Task<WebCams.Servicio.Usuario> agregarUsuarioAsync(string nombre, string apellido, string pasaporte, string mail, string fechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/getTwitter", ReplyAction="http://tempuri.org/IServicioAEI/getTwitterResponse")]
        WebCams.Servicio.Twitter getTwitter(string screenName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/getTwitter", ReplyAction="http://tempuri.org/IServicioAEI/getTwitterResponse")]
        System.Threading.Tasks.Task<WebCams.Servicio.Twitter> getTwitterAsync(string screenName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/agregarTwitter", ReplyAction="http://tempuri.org/IServicioAEI/agregarTwitterResponse")]
        int agregarTwitter(string idUsuario, string screenName, string OauthToken, string OauthTokenSecret);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/agregarTwitter", ReplyAction="http://tempuri.org/IServicioAEI/agregarTwitterResponse")]
        System.Threading.Tasks.Task<int> agregarTwitterAsync(string idUsuario, string screenName, string OauthToken, string OauthTokenSecret);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/buscarCalificacionProducto", ReplyAction="http://tempuri.org/IServicioAEI/buscarCalificacionProductoResponse")]
        System.Collections.Generic.List<WebCams.Servicio.Calificacion> buscarCalificacionProducto(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/buscarCalificacionProducto", ReplyAction="http://tempuri.org/IServicioAEI/buscarCalificacionProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Calificacion>> buscarCalificacionProductoAsync(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/BuscarProductoPorCategoria", ReplyAction="http://tempuri.org/IServicioAEI/BuscarProductoPorCategoriaResponse")]
        System.Collections.Generic.List<WebCams.Servicio.Producto> BuscarProductoPorCategoria(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/BuscarProductoPorCategoria", ReplyAction="http://tempuri.org/IServicioAEI/BuscarProductoPorCategoriaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Producto>> BuscarProductoPorCategoriaAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/BusquedaProductoConCategoria", ReplyAction="http://tempuri.org/IServicioAEI/BusquedaProductoConCategoriaResponse")]
        System.Collections.Generic.List<WebCams.Servicio.Producto> BusquedaProductoConCategoria(string categoriaProducto, string busqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/BusquedaProductoConCategoria", ReplyAction="http://tempuri.org/IServicioAEI/BusquedaProductoConCategoriaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Producto>> BusquedaProductoConCategoriaAsync(string categoriaProducto, string busqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/BusquedaProducto", ReplyAction="http://tempuri.org/IServicioAEI/BusquedaProductoResponse")]
        System.Collections.Generic.List<WebCams.Servicio.Producto> BusquedaProducto(string busqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/BusquedaProducto", ReplyAction="http://tempuri.org/IServicioAEI/BusquedaProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Producto>> BusquedaProductoAsync(string busqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/BuscarTodasLasCategorias", ReplyAction="http://tempuri.org/IServicioAEI/BuscarTodasLasCategoriasResponse")]
        System.Collections.Generic.List<WebCams.Servicio.Categoria> BuscarTodasLasCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/BuscarTodasLasCategorias", ReplyAction="http://tempuri.org/IServicioAEI/BuscarTodasLasCategoriasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Categoria>> BuscarTodasLasCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/consultarEstados", ReplyAction="http://tempuri.org/IServicioAEI/consultarEstadosResponse")]
        System.Collections.Generic.List<WebCams.Servicio.Direccion> consultarEstados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/consultarEstados", ReplyAction="http://tempuri.org/IServicioAEI/consultarEstadosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Direccion>> consultarEstadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/consultarCiudad", ReplyAction="http://tempuri.org/IServicioAEI/consultarCiudadResponse")]
        System.Collections.Generic.List<WebCams.Servicio.Direccion> consultarCiudad(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/consultarCiudad", ReplyAction="http://tempuri.org/IServicioAEI/consultarCiudadResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Direccion>> consultarCiudadAsync(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/agregarDireccionUsuario", ReplyAction="http://tempuri.org/IServicioAEI/agregarDireccionUsuarioResponse")]
        int agregarDireccionUsuario(int idUsuario, int idDireccion, string descripcion, int codigoPostal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/agregarDireccionUsuario", ReplyAction="http://tempuri.org/IServicioAEI/agregarDireccionUsuarioResponse")]
        System.Threading.Tasks.Task<int> agregarDireccionUsuarioAsync(int idUsuario, int idDireccion, string descripcion, int codigoPostal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/agregarCarrito", ReplyAction="http://tempuri.org/IServicioAEI/agregarCarritoResponse")]
        WebCams.Servicio.Usuario agregarCarrito(WebCams.Servicio.Usuario usuario, WebCams.Servicio.DetalleCompra detalleCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/agregarCarrito", ReplyAction="http://tempuri.org/IServicioAEI/agregarCarritoResponse")]
        System.Threading.Tasks.Task<WebCams.Servicio.Usuario> agregarCarritoAsync(WebCams.Servicio.Usuario usuario, WebCams.Servicio.DetalleCompra detalleCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/buscarDireccionUsuario", ReplyAction="http://tempuri.org/IServicioAEI/buscarDireccionUsuarioResponse")]
        System.Collections.Generic.List<WebCams.Servicio.Direccion> buscarDireccionUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAEI/buscarDireccionUsuario", ReplyAction="http://tempuri.org/IServicioAEI/buscarDireccionUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Direccion>> buscarDireccionUsuarioAsync(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAEIChannel : WebCams.Servicio.IServicioAEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAEIClient : System.ServiceModel.ClientBase<WebCams.Servicio.IServicioAEI>, WebCams.Servicio.IServicioAEI {
        
        public ServicioAEIClient() {
        }
        
        public ServicioAEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int modificarStatusCompra(int idCompra) {
            return base.Channel.modificarStatusCompra(idCompra);
        }
        
        public System.Threading.Tasks.Task<int> modificarStatusCompraAsync(int idCompra) {
            return base.Channel.modificarStatusCompraAsync(idCompra);
        }
        
        public WebCams.Servicio.Usuario modificarMetodoPago(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Usuario usuario, int metodoActual) {
            return base.Channel.modificarMetodoPago(metodo, usuario, metodoActual);
        }
        
        public System.Threading.Tasks.Task<WebCams.Servicio.Usuario> modificarMetodoPagoAsync(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Usuario usuario, int metodoActual) {
            return base.Channel.modificarMetodoPagoAsync(metodo, usuario, metodoActual);
        }
        
        public string generarXml(int idCompra) {
            return base.Channel.generarXml(idCompra);
        }
        
        public System.Threading.Tasks.Task<string> generarXmlAsync(int idCompra) {
            return base.Channel.generarXmlAsync(idCompra);
        }
        
        public int enviarCorreoDeFactura(WebCams.Servicio.Usuario usuario, WebCams.Servicio.Compra compra) {
            return base.Channel.enviarCorreoDeFactura(usuario, compra);
        }
        
        public System.Threading.Tasks.Task<int> enviarCorreoDeFacturaAsync(WebCams.Servicio.Usuario usuario, WebCams.Servicio.Compra compra) {
            return base.Channel.enviarCorreoDeFacturaAsync(usuario, compra);
        }
        
        public WebCams.Servicio.Usuario agregarMetodoPago(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Usuario usuario) {
            return base.Channel.agregarMetodoPago(metodo, usuario);
        }
        
        public System.Threading.Tasks.Task<WebCams.Servicio.Usuario> agregarMetodoPagoAsync(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Usuario usuario) {
            return base.Channel.agregarMetodoPagoAsync(metodo, usuario);
        }
        
        public int modificarDireccion(WebCams.Servicio.Direccion direccionModificada) {
            return base.Channel.modificarDireccion(direccionModificada);
        }
        
        public System.Threading.Tasks.Task<int> modificarDireccionAsync(WebCams.Servicio.Direccion direccionModificada) {
            return base.Channel.modificarDireccionAsync(direccionModificada);
        }
        
        public WebCams.Servicio.Usuario checkout(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Direccion direccion, WebCams.Servicio.Usuario usuario) {
            return base.Channel.checkout(metodo, direccion, usuario);
        }
        
        public System.Threading.Tasks.Task<WebCams.Servicio.Usuario> checkoutAsync(WebCams.Servicio.MetodoPago metodo, WebCams.Servicio.Direccion direccion, WebCams.Servicio.Usuario usuario) {
            return base.Channel.checkoutAsync(metodo, direccion, usuario);
        }
        
        public bool disponibilidadProductos(System.Collections.Generic.List<WebCams.Servicio.DetalleCompra> detalle) {
            return base.Channel.disponibilidadProductos(detalle);
        }
        
        public System.Threading.Tasks.Task<bool> disponibilidadProductosAsync(System.Collections.Generic.List<WebCams.Servicio.DetalleCompra> detalle) {
            return base.Channel.disponibilidadProductosAsync(detalle);
        }
        
        public bool checkearProductoCarrito(WebCams.Servicio.Usuario usuario, WebCams.Servicio.Producto producto) {
            return base.Channel.checkearProductoCarrito(usuario, producto);
        }
        
        public System.Threading.Tasks.Task<bool> checkearProductoCarritoAsync(WebCams.Servicio.Usuario usuario, WebCams.Servicio.Producto producto) {
            return base.Channel.checkearProductoCarritoAsync(usuario, producto);
        }
        
        public WebCams.Servicio.Usuario borrarDetalleCarrito(WebCams.Servicio.Usuario usuario, WebCams.Servicio.DetalleCompra detalle) {
            return base.Channel.borrarDetalleCarrito(usuario, detalle);
        }
        
        public System.Threading.Tasks.Task<WebCams.Servicio.Usuario> borrarDetalleCarritoAsync(WebCams.Servicio.Usuario usuario, WebCams.Servicio.DetalleCompra detalle) {
            return base.Channel.borrarDetalleCarritoAsync(usuario, detalle);
        }
        
        public int enviarCorreoDeModificacion(WebCams.Servicio.Usuario usuario) {
            return base.Channel.enviarCorreoDeModificacion(usuario);
        }
        
        public System.Threading.Tasks.Task<int> enviarCorreoDeModificacionAsync(WebCams.Servicio.Usuario usuario) {
            return base.Channel.enviarCorreoDeModificacionAsync(usuario);
        }
        
        public int enviarCorreoDeBienvenida(WebCams.Servicio.Usuario usuario) {
            return base.Channel.enviarCorreoDeBienvenida(usuario);
        }
        
        public System.Threading.Tasks.Task<int> enviarCorreoDeBienvenidaAsync(WebCams.Servicio.Usuario usuario) {
            return base.Channel.enviarCorreoDeBienvenidaAsync(usuario);
        }
        
        public int modificarUsuario(WebCams.Servicio.Usuario usuario) {
            return base.Channel.modificarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<int> modificarUsuarioAsync(WebCams.Servicio.Usuario usuario) {
            return base.Channel.modificarUsuarioAsync(usuario);
        }
        
        public WebCams.Servicio.Usuario ConsultarUsuario(string mail) {
            return base.Channel.ConsultarUsuario(mail);
        }
        
        public System.Threading.Tasks.Task<WebCams.Servicio.Usuario> ConsultarUsuarioAsync(string mail) {
            return base.Channel.ConsultarUsuarioAsync(mail);
        }
        
        public WebCams.Servicio.Usuario agregarUsuario(string nombre, string apellido, string pasaporte, string mail, string fechaNacimiento) {
            return base.Channel.agregarUsuario(nombre, apellido, pasaporte, mail, fechaNacimiento);
        }
        
        public System.Threading.Tasks.Task<WebCams.Servicio.Usuario> agregarUsuarioAsync(string nombre, string apellido, string pasaporte, string mail, string fechaNacimiento) {
            return base.Channel.agregarUsuarioAsync(nombre, apellido, pasaporte, mail, fechaNacimiento);
        }
        
        public WebCams.Servicio.Twitter getTwitter(string screenName) {
            return base.Channel.getTwitter(screenName);
        }
        
        public System.Threading.Tasks.Task<WebCams.Servicio.Twitter> getTwitterAsync(string screenName) {
            return base.Channel.getTwitterAsync(screenName);
        }
        
        public int agregarTwitter(string idUsuario, string screenName, string OauthToken, string OauthTokenSecret) {
            return base.Channel.agregarTwitter(idUsuario, screenName, OauthToken, OauthTokenSecret);
        }
        
        public System.Threading.Tasks.Task<int> agregarTwitterAsync(string idUsuario, string screenName, string OauthToken, string OauthTokenSecret) {
            return base.Channel.agregarTwitterAsync(idUsuario, screenName, OauthToken, OauthTokenSecret);
        }
        
        public System.Collections.Generic.List<WebCams.Servicio.Calificacion> buscarCalificacionProducto(int idProducto) {
            return base.Channel.buscarCalificacionProducto(idProducto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Calificacion>> buscarCalificacionProductoAsync(int idProducto) {
            return base.Channel.buscarCalificacionProductoAsync(idProducto);
        }
        
        public System.Collections.Generic.List<WebCams.Servicio.Producto> BuscarProductoPorCategoria(string nombre) {
            return base.Channel.BuscarProductoPorCategoria(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Producto>> BuscarProductoPorCategoriaAsync(string nombre) {
            return base.Channel.BuscarProductoPorCategoriaAsync(nombre);
        }
        
        public System.Collections.Generic.List<WebCams.Servicio.Producto> BusquedaProductoConCategoria(string categoriaProducto, string busqueda) {
            return base.Channel.BusquedaProductoConCategoria(categoriaProducto, busqueda);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Producto>> BusquedaProductoConCategoriaAsync(string categoriaProducto, string busqueda) {
            return base.Channel.BusquedaProductoConCategoriaAsync(categoriaProducto, busqueda);
        }
        
        public System.Collections.Generic.List<WebCams.Servicio.Producto> BusquedaProducto(string busqueda) {
            return base.Channel.BusquedaProducto(busqueda);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Producto>> BusquedaProductoAsync(string busqueda) {
            return base.Channel.BusquedaProductoAsync(busqueda);
        }
        
        public System.Collections.Generic.List<WebCams.Servicio.Categoria> BuscarTodasLasCategorias() {
            return base.Channel.BuscarTodasLasCategorias();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Categoria>> BuscarTodasLasCategoriasAsync() {
            return base.Channel.BuscarTodasLasCategoriasAsync();
        }
        
        public System.Collections.Generic.List<WebCams.Servicio.Direccion> consultarEstados() {
            return base.Channel.consultarEstados();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Direccion>> consultarEstadosAsync() {
            return base.Channel.consultarEstadosAsync();
        }
        
        public System.Collections.Generic.List<WebCams.Servicio.Direccion> consultarCiudad(int idEstado) {
            return base.Channel.consultarCiudad(idEstado);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Direccion>> consultarCiudadAsync(int idEstado) {
            return base.Channel.consultarCiudadAsync(idEstado);
        }
        
        public int agregarDireccionUsuario(int idUsuario, int idDireccion, string descripcion, int codigoPostal) {
            return base.Channel.agregarDireccionUsuario(idUsuario, idDireccion, descripcion, codigoPostal);
        }
        
        public System.Threading.Tasks.Task<int> agregarDireccionUsuarioAsync(int idUsuario, int idDireccion, string descripcion, int codigoPostal) {
            return base.Channel.agregarDireccionUsuarioAsync(idUsuario, idDireccion, descripcion, codigoPostal);
        }
        
        public WebCams.Servicio.Usuario agregarCarrito(WebCams.Servicio.Usuario usuario, WebCams.Servicio.DetalleCompra detalleCompra) {
            return base.Channel.agregarCarrito(usuario, detalleCompra);
        }
        
        public System.Threading.Tasks.Task<WebCams.Servicio.Usuario> agregarCarritoAsync(WebCams.Servicio.Usuario usuario, WebCams.Servicio.DetalleCompra detalleCompra) {
            return base.Channel.agregarCarritoAsync(usuario, detalleCompra);
        }
        
        public System.Collections.Generic.List<WebCams.Servicio.Direccion> buscarDireccionUsuario(int idUsuario) {
            return base.Channel.buscarDireccionUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebCams.Servicio.Direccion>> buscarDireccionUsuarioAsync(int idUsuario) {
            return base.Channel.buscarDireccionUsuarioAsync(idUsuario);
        }
    }
}
